apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "react-vite-app"
  description: "A sample React application created from backstage software templates."
  annotations:
    github.com/project-slug: karthikjeeyar/react-app
spec:
  type: website
  lifecycle: experimental
  owner: "group:default/karthikjeeyar"
